# .github/workflows/run_sort_recipe.yml
name: Run sort_recipe_by_cooking_time

on:
  push:
    branches:
      - xin/automation

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # or specify '3.11' etc.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run sort_recipes_by_cooking_time.py
        run: python tools/sort_recipes_by_cooking_time.py

      - name: Commit and push sorted recipes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add recipes/sorted_recipes_by_cooking_time.yaml

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update sorted recipes [auto]"
            git push
          fi


