name: Weekly Meal Planning

on:
  schedule:
    # Run every Friday at 10 PM Eastern Time
    # During EST (Nov-Mar): 10 PM EST = 3 AM UTC the following day
    # During EDT (Mar-Nov): 5 PM EDT = 2 AM UTC the following day
    # Using 3 AM UTC on Saturday
    - cron: '0 3 * * 6'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  plan-weekly-meals:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run weekly meal planner
      run: |
        python tools/plan_week.py --save-grocery-list weekly_groceries.txt
        
    - name: Upload meal plan artifacts
      uses: actions/upload-artifact@v4
      with:
        name: weekly-meal-plan
        path: |
          weekly_groceries.txt
          weekly_meal_plan.ics
        retention-days: 7

    - name: Prepare calendar folder
      run: |
        mkdir -p calendar
        cp weekly_meal_plan.ics calendar/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./calendar

